[package]
name = "demonstrator"
version = "0.1.0"
edition = "2024"


[target.'cfg(target_arch = "x86_64")'.dependencies]
macroquad = "0.4.13"

[target.'cfg(not(target_arch = "x86_64"))'.dependencies]
blinkt = "0.7.1"

[dependencies]
glam = "0.30.9"
palette = "0.7.6"
serialport = "4.7.2"
